server:
  port: 8080

spring:
  application:
    name: deepak-portfolio
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio
    username: ${DB_USERNAME:portfolio_user}
    password: ${DB_PASSWORD:portfolio_pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  graphql:
    graphiql:
      enabled: true
      path: /graphiql

logging:
  level:
    com.deepaknalla.portfolio: DEBUG